
const dummyData = {
  _id: '5e745ccd13ecb588a415e114',
  restaurant: 'blue Implemented Licensed Steel Pizza',
  id: 34,
  photo: [
    {
      _id: '5e745ccd13ecb588a415e115',
      url: 'https://picsum.photos/id/263/1200/860',
      caption: 'Dolor soluta nesciunt quod nulla nemo quia blanditiis molestias omnis.',
      ownersubmitted: false,
      rating: '1',
      username: 'Maurice_Ryan5',
      thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/safrankov/128.jpg',
    },
    {
      _id: '5e745ccd13ecb588a415e116',
      url: 'https://picsum.photos/id/264/1200/860',
      caption: 'Labore qui eos et laudantium.',
      ownersubmitted: false,
      rating: '2',
      username: 'Carlie.Shanahan',
      thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/adrienths/128.jpg',
    },
    {
      _id: '5e745ccd13ecb588a415e117',
      url: 'https://picsum.photos/id/265/1200/860',
      caption: 'Repellat ut suscipit.',
      ownersubmitted: true,
      rating: '2',
      username: 'Vicky61',
      thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/tom_even/128.jpg',
    },
    {
      _id: '5e745ccd13ecb588a415e118',
      url: 'https://picsum.photos/id/266/1200/860',
      caption: 'Qui voluptas tempore quia.',
      ownersubmitted: true,
      rating: '3',
      username: 'Ruthe.Bode',
      thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/anaami/128.jpg',
    },
    {
      _id: '5e745ccd13ecb588a415e119',
      url: 'https://picsum.photos/id/267/1200/860',
      caption: 'Culpa accusantium expedita facere occaecati sint accusantium omnis nostrum et.',
      ownersubmitted: true,
      rating: '5',
      username: 'Ignacio.Pfeffer84',
      thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/rawdiggie/128.jpg',
    },
    {
      _id: '5e745ccd13ecb588a415e11a',
      url: 'https://picsum.photos/id/268/1200/860',
      caption: 'Quasi dolor enim omnis quo at et.',
      ownersubmitted: false,
      rating: '5',
      username: 'Rod_Lindgren',
      thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/benefritz/128.jpg',
    },
    {
      _id: '5e745ccd13ecb588a415e11b',
      url: 'https://picsum.photos/id/269/1200/860',
      caption: 'Nam delectus optio ullam ut mollitia mollitia eos.',
      ownersubmitted: true,
      rating: '1',
      username: 'Sammy.Rutherford',
      thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/kerem/128.jpg',
    },
    {
      _id: '5e745ccd13ecb588a415e11b',
      url: 'https://picsum.photos/id/269/1200/860',
      caption: 'Nam delectus optio ullam ut mollitia mollitia eos.',
      ownersubmitted: true,
      rating: '1',
      username: 'Sammy.Rutherford',
      thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/kerem/128.jpg',
    },
    {
      _id: '5e745ccd13ecb588a415e11b',
      url: 'https://picsum.photos/id/269/1200/860',
      caption: 'Nam delectus optio ullam ut mollitia mollitia eos.',
      ownersubmitted: true,
      rating: '1',
      username: 'Sammy.Rutherford',
      thumbnail: 'https://s3.amazonaws.com/uifaces/faces/twitter/kerem/128.jpg',
    },
  ],
  __v: 0,
};

export default dummyData;
